# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a0f22330b5c88613d1c5c28603c505c0f71f9a154c03fb051667575a4db5f98edf50de02ab1f52dead2b99ca99b977099bbb0d1af6c72d0bf2df59f0d4ffb04

test:
  secret_key_base: 35529642a3a3a878dd9b8b2aaaf45acd1465298d026fe36573a3e812cfd63eb7147c45bf39d2f1199fbe10596c904d508a6df6e3dec8df5bd379b5232a1a8a2e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
